Zadanie 1:

In [33]:
import numpy as np

def jacobi_solve(A: np.matrix, b: np.matrix, ite = 500) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum = sum + A[i,j] * x[j]
            x1[i] = (1 / A[i,i]) * (b[i] - sum)
        x = x1
        k = k + 1
    return x

In [34]:
#przykładowe układy równań
import numpy as np

A1 = np.matrix([[2, 1, 1],
               [2, 2, 4],
               [1, 4, 3]])

b1 = np.matrix([1, 3, 8]).transpose()

A2 = np.matrix([[4, -1, -0.2, 2],
               [-1, 5, 0, -2],
               [0.2, 1, 10, -1],
               [0, -2, -1, 4]])

b2 = np.matrix([30, 0, -10, 5]).transpose()

res1 = jacobi_solve(A1, b1)
res2 = jacobi_solve(A2, b2)
print(res1)
print(res2)

[-5.19389118e+145 -1.15955182e+146 -8.76934907e+145]
[ 6.96156056  2.22112253 -1.15414086  2.07202605]


Zadanie 2:

In [35]:
import numpy as np
def gauss_seidel_solve(A: np.matrix, b: np.matrix, ite = 500) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum = sum + A[i,j] * x[j]
            x1[i] = (1 / A[i,i]) * (b[i] - sum)
        x = x1
        k = k + 1
    return x

In [36]:
#przykładowe układy równań
import numpy as np

A1 = np.matrix([[2, 1, 1],
               [2, 2, 4],
               [1, 4, 3]])

b1 = np.matrix([1, 3, 8]).transpose()

A2 = np.matrix([[4, -1, -0.2, 2],
               [-1, 5, 0, -2],
               [0.2, 1, 10, -1],
               [0, -2, -1, 4]])

b2 = np.matrix([30, 0, -10, 5]).transpose()

res1 = gauss_seidel_solve(A1, b1)
res2 = gauss_seidel_solve(A2, b2)
print(res1)
print(res2)

[-5.19389118e+145 -1.15955182e+146 -8.76934907e+145]
[ 6.96156056  2.22112253 -1.15414086  2.07202605]


Zadanie 3:

In [37]:
def sor_solve(A: np.matrix, b: np.matrix, ite = 500) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    omega = 1.44
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sumL = 0
            sumU = 0
            for j in range(0, i):
                sumL = sumL + A[i,j] * x1[j]
            for j in range(i+1, n):
                sumU = sumU + A[i,j] * x[j]
            x1[i] = (1 - omega) * x[i] + (omega / A[i,i]) * (b[i] - sumL - sumU)
        x = x1
        k = k + 1
    return x

In [38]:
#przykładowe układy równań
import numpy as np

A1 = np.matrix([[2, 1, 1],
               [2, 2, 4],
               [1, 4, 3]])

b1 = np.matrix([1, 3, 8]).transpose()

A2 = np.matrix([[4, -1, -0.2, 2],
               [-1, 5, 0, -2],
               [0.2, 1, 10, -1],
               [0, -2, -1, 4]])

b2 = np.matrix([30, 0, -10, 5]).transpose()

res1 = sor_solve(A1, b1)
res2 = sor_solve(A2, b2)
print(res1)
print(res2)

[-2.85560442e+297 -2.22985234e+298  3.97708953e+298]
[ 6.96156056  2.22112253 -1.15414086  2.07202605]


Zadanie 4:

In [39]:
def check(A, b, solve):
    xt = np.linalg.solve(A2, b2)
    for i in range(1,25):
        x = solve(A2, b2, i)
        if(np.allclose(xt.transpose(), x) == True):
            print("the best result", i, "iterations")
            break
            
A2 = np.matrix([[4, -1, -0.2, 2],
               [-1, 5, 0, -2],
               [0.2, 1, 10, -1],
               [0, -2, -1, 4]])

b2 = np.matrix([30, 0, -10, 5]).transpose()

check(A2, b2, sor_solve)
check(A2, b2, gauss_seidel_solve)
check(A2, b2, jacobi_solve)

the best result 20 iterations
the best result 22 iterations
the best result 22 iterations
