Zadanie 1:

In [7]:
def agh_superfast_matrix_multiply(a: np.matrix, b: np.matrix) -> np.matrix:

    n = a.shape[0]
    m = a.shape[1]
    p = b.shape[1]
    c = np.zeros((n,p))
    
    for i in range(0,n):
        for j in range(0,p):
            for k in range(0,m):
                c[i,j] += a[i,k] * b[k,j]
    return c

m1 = np.matrix([[1, 2],
                [3, 4],
                [4, 5],
                [5, 1]])

m2 = np.matrix([[1, 2, 3],
                [4, 5, 6]])


res = agh_superfast_matrix_multiply(m1, m2)
print(res)
assert np.allclose(res, m1 * m2), "Wrong multiplication result"

[[ 9. 12. 15.]
 [19. 26. 33.]
 [24. 33. 42.]
 [ 9. 15. 21.]]


Zadanie 2:

In [8]:
#eliminacja Gausa bez pivotingu

def non_pivot_gauss(A, b):
    n = len(A)
    A = np.copy(A)
    b = np.copy(b)
    
    for i in range(n):
        for j in range(n):
            if i != j:
                scale = A[j, i]/A[i, i]
                A[j] -= A[i]*scale
                b[j] -= b[i]*scale

    for i in range(n):
        b[i] /= A[i, i]
        
    return b


#eliminacja Gaussa z pivotingiem

def pivot_gauss(A, b):
    n = len(A)
    A = np.copy(A)
    b = np.copy(b)
    
    for i in range(n-1):
        maxidx = abs(A[i:,i]).argmax() + i
        if maxidx != i:
            A[[i,maxidx]] = A[[maxidx, i]]
            b[[i,maxidx]] = b[[maxidx, i]]
            
        for row in range(i+1, n):
            scale = A[row,i]/A[i,i]
            A[row, i:] = A[row, i:] - scale*A[i, i:]
            b[row] = b[row] - scale*b[i]

    for i in range(n-1, -1, -1):
        b[i] = (b[i] - np.dot(A[i,i+1:], b[i+1:])) / A[i,i]
        
    return b


#rozwiązanie układu rówań powyższymi metodami i porównanie wyników

import numpy as np

A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

x = np.linalg.solve(A, b)
y = non_pivot_gauss(A, b)
z = pivot_gauss(A, b)

np.allclose(x, y), np.allclose(x, z)

(True, True)

Zadanie 3:

In [13]:
#algorytm faktoryzacji LU macierzy

from typing import Optional, Tuple

def agh_superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    n = a.shape[0]
    l = np.zeros((n,n))
    u = np.zeros((n,n))
    
    for k in range(0,n):
        l[k,k] = 1
        for j in range(k,n):
            sum = 0
            for s in range(0,k):
                sum += l[k,s] * u[s,j]
            u[k,j] = a[k,j] - sum
        for i in range(k+1,n):
            sum = 0
            for s in range(0,k):
                sum += l[i,s] * u[s,k]
            l[i,k] = (a[i,k] - sum) / u[k,k]
    return (l, u)

Zadanie 4: 

In [14]:
#sprawdzanie czy macierz jest symetryczna i dodatnio określona

def agh_superfast_check_spd(a: np.matrix) -> bool:
    l = agh_superfast_cholesky(a)
    llt = agh_superfast_matrix_multiply(l, l.transpose())
    return np.allclose(llt, a)

Zadanie 5:

In [15]:
#algorytm faktoryzacji Cholesky'ego macierzy

def agh_superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    n = a.shape[0]
    l = np.zeros((n,n))
    
    for k in range(0,n):
        sum = 0
        for s in range(0,k):
            sum += l[k,s] * l[k,s]
        l[k,k] = pow(a[k,k] - sum, 1/2)
        for i in range(k+1,n):
            sum = 0
            for s in range(0,k):
                sum += l[i,s] * l[k,s]
            l[i,k] = (a[i,k] - sum) / l[k,k]
    return l